// webcomponents/school-erp-wireframe/components/ui-datepicker.js
import { BaseElement, attr } from './base.js';

/**
 * Single-date picker with a calendar popover.
 *
 * <ui-datepicker label="Date of birth" value="2015-08-12"></ui-datepicker>
 *
 * Emits `change` with { value } in ISO (YYYY-MM-DD).
 */
class UIDatepicker extends BaseElement {
  static styles = `
    :host { display: inline-block; position: relative; box-sizing: border-box; z-index: auto; }
    /* When open, host becomes a very high stacking context so the (fixed)
       popover paints above sticky topbar / bottom nav even inside modals. */
    :host([open]) { z-index: 3000; }
    .label {
      display: block; font-size: var(--fs-xs); color: var(--color-text-muted);
      margin-bottom: 6px; font-weight: var(--fw-medium);
    }
    .trigger {
      display: inline-flex; align-items: center; gap: 8px;
      background: var(--color-surface);
      border: 1px solid var(--color-border-strong);
      border-radius: var(--radius-md);
      height: 40px; padding: 0 12px;
      font: inherit; font-size: var(--fs-sm); color: var(--color-text);
      cursor: pointer; min-width: 180px;
      transition: border-color var(--dur-fast) var(--ease), box-shadow var(--dur-fast) var(--ease);
    }
    .trigger:hover { border-color: var(--color-text-subtle); }
    .trigger:focus { outline: none; box-shadow: var(--shadow-focus); border-color: var(--color-primary); }
    .trigger ui-icon { color: var(--color-text-muted); }
    .trigger .val { flex: 1; }
    .trigger .placeholder { color: var(--color-text-subtle); }
    .trigger .caret { color: var(--color-text-subtle); }

    .pop {
      position: absolute; top: calc(100% + 6px); left: 0;
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-lg);
      box-shadow: var(--shadow-lg);
      /* Sits above sticky topbar (20), bottom nav (30) and shell chrome.
         Modal (2000) is still above so pickers inside modals overlay too. */
      z-index: 1000;
      display: none;
      padding: 12px;
      width: 280px;
      max-width: calc(100vw - 24px);
    }
    /* Scrim behind the mobile bottom sheet */
    .scrim {
      position: fixed; inset: 0;
      background: var(--color-scrim);
      z-index: 999; display: none;
      animation: sc-in var(--dur-med) var(--ease);
    }
    :host([open]) .scrim { display: block; }
    @keyframes sc-in { from { opacity: 0; } to { opacity: 1; } }
    @media (min-width: 641px) { .scrim { display: none !important; } }
    :host([data-align="right"]) .pop { left: auto; right: 0; }
    /* On mobile, the popover is fixed to the viewport bottom, so
       the desktop right-align rule must NOT apply. */
    @media (max-width: 640px) {
      :host([data-align="right"]) .pop { left: 8px; right: 8px; }
    }
    :host([open]) .pop { display: block; }

    .head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px; }
    .head .month { font-weight: var(--fw-semibold); font-size: var(--fs-sm); }
    .nav-btn {
      appearance: none; border: 0; background: transparent; cursor: pointer;
      color: var(--color-text-muted); width: 26px; height: 26px;
      border-radius: 6px; display: grid; place-items: center;
    }
    .nav-btn:hover { background: color-mix(in srgb, var(--color-text) 8%, transparent); color: var(--color-text); }

    .dow, .grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 2px; }
    .dow div {
      font-size: 10px; color: var(--color-text-subtle); text-align: center;
      padding: 4px 0; font-weight: var(--fw-medium);
    }
    .grid button {
      appearance: none; border: 0; background: transparent;
      font: inherit; font-size: var(--fs-xs); color: var(--color-text);
      height: 32px; cursor: pointer;
      border-radius: 6px;
      display: grid; place-items: center;
      font-variant-numeric: tabular-nums;
    }
    .grid button:hover { background: color-mix(in srgb, var(--color-text) 8%, transparent); }
    .grid button.muted { color: var(--color-text-subtle); }
    .grid button.today { box-shadow: inset 0 0 0 1px var(--color-primary); color: var(--color-primary); font-weight: var(--fw-semibold); }
    .grid button.sel { background: var(--color-primary); color: var(--color-primary-contrast); font-weight: var(--fw-semibold); }

    .foot { margin-top: 10px; display: flex; justify-content: space-between; gap: 8px; }
    .foot .today-link {
      appearance: none; border: 0; background: transparent; cursor: pointer;
      color: var(--color-primary); font: inherit; font-size: var(--fs-xs); font-weight: var(--fw-medium);
    }

    /* Mobile: fixed bottom-sheet, sits above the bottom nav */
    @media (max-width: 640px) {
      .pop {
        position: fixed;
        left: 8px; right: 8px; top: auto;
        bottom: calc(var(--bottomnav-h, 62px) + 16px + env(safe-area-inset-bottom, 0));
        width: auto; max-width: none;
        padding: 16px;
        border-radius: var(--radius-xl);
        animation: dp-slide-up var(--dur-med) var(--ease);
      }
      @keyframes dp-slide-up { from { transform: translateY(24px); opacity: 0; } to { transform: none; opacity: 1; } }
      .grid button { height: 40px; font-size: var(--fs-sm); }
      .dow div { font-size: 11px; padding: 6px 0; }
    }
  `;

  static get observedAttributes() { return ['value']; }

  constructor() {
    super();
    this._val = null;
    this._viewYear = null;
    this._viewMonth = null;
    this._boundOutside = (e) => { if (!this.contains(e.target)) this._close(); };
  }

  connectedCallback() {
    this._val = this._parse(attr(this, 'value'));
    const ref = this._val || new Date();
    this._viewYear = ref.getFullYear();
    this._viewMonth = ref.getMonth();
    super.connectedCallback();
  }

  render() {
    const label = attr(this, 'label');
    return `
      ${label ? `<span class="label">${label}</span>` : ''}
      <button class="trigger" type="button" data-role="trigger">
        <ui-icon name="calendar" size="16"></ui-icon>
        <span class="val" data-role="text">${this._fmtDisplay()}</span>
        <ui-icon class="caret" name="chevronDown" size="14"></ui-icon>
      </button>
      <div class="scrim" data-role="scrim"></div>
      <div class="pop" role="dialog">
        <div class="head">
          <button class="nav-btn" data-nav="-1"><ui-icon name="chevronRight" size="14" style="transform: rotate(180deg)"></ui-icon></button>
          <span class="month" data-role="month"></span>
          <button class="nav-btn" data-nav="+1"><ui-icon name="chevronRight" size="14"></ui-icon></button>
        </div>
        <div class="dow"><div>M</div><div>T</div><div>W</div><div>T</div><div>F</div><div>S</div><div>S</div></div>
        <div class="grid" data-role="grid"></div>
        <div class="foot">
          <button class="today-link" data-action="today">Today</button>
          <button class="today-link" data-action="clear" style="color:var(--color-text-muted)">Clear</button>
        </div>
      </div>
    `;
  }

  afterRender() {
    this.$('[data-role="trigger"]').addEventListener('click', (e) => {
      e.stopPropagation();
      this.hasAttribute('open') ? this._close() : this._open();
    });
    this.$$('.nav-btn').forEach(b => b.addEventListener('click', () => {
      this._viewMonth += parseInt(b.dataset.nav, 10);
      if (this._viewMonth < 0) { this._viewMonth = 11; this._viewYear--; }
      if (this._viewMonth > 11) { this._viewMonth = 0;  this._viewYear++; }
      this._renderGrid();
    }));
    this.shadowRoot.addEventListener('click', (e) => {
      const b = e.target.closest('[data-action]');
      if (!b) return;
      if (b.dataset.action === 'today') { this._val = this._startOfDay(new Date()); this._sync(); }
      if (b.dataset.action === 'clear') { this._val = null; this._sync(); }
    });
    this._renderGrid();
  }

  _open() {
    this.setAttribute('open', '');
    this._positionPop();
    document.addEventListener('mousedown', this._boundOutside);
    window.addEventListener('resize',  this._boundReposition = () => this._positionPop());
    window.addEventListener('scroll',  this._boundReposition, true);
  }
  _close() {
    this.removeAttribute('open');
    document.removeEventListener('mousedown', this._boundOutside);
    if (this._boundReposition) {
      window.removeEventListener('resize', this._boundReposition);
      window.removeEventListener('scroll', this._boundReposition, true);
    }
  }
  _positionPop() {
    const trigger = this.$('[data-role="trigger"]');
    const pop     = this.$('.pop');
    if (!trigger || !pop) return;
    const isMobile = window.matchMedia('(max-width: 640px)').matches;
    if (isMobile) { pop.style.cssText = ''; return; }
    // Predictable anchor: always below the trigger, aligned to its LEFT edge.
    // The only adjustment we make is clamping inside the viewport so it
    // never renders off-screen.
    const r = trigger.getBoundingClientRect();
    const POP_W = 280, POP_H = 340, GAP = 6;
    let top  = r.bottom + GAP;
    let left = r.left;
    // Clamp right/bottom edges
    if (left + POP_W > window.innerWidth  - 8) left = window.innerWidth  - POP_W - 8;
    if (top  + POP_H > window.innerHeight - 8) top  = window.innerHeight - POP_H - 8;
    pop.style.position = 'fixed';
    pop.style.top  = `${Math.max(8, top)}px`;
    pop.style.left = `${Math.max(8, left)}px`;
    pop.style.right = 'auto';
    pop.style.bottom = 'auto';
  }

  _renderGrid() {
    const y = this._viewYear, m = this._viewMonth;
    this.$('[data-role="month"]').textContent =
      new Date(y, m, 1).toLocaleString(undefined, { month: 'long', year: 'numeric' });
    const first = new Date(y, m, 1);
    const startDow = (first.getDay() + 6) % 7;
    const daysInMonth = new Date(y, m + 1, 0).getDate();
    const prev = new Date(y, m, 0).getDate();
    const cells = [];
    for (let i = startDow - 1; i >= 0; i--) cells.push({ d: prev - i, muted: true, date: new Date(y, m - 1, prev - i) });
    for (let d = 1; d <= daysInMonth; d++)  cells.push({ d, muted: false, date: new Date(y, m, d) });
    while (cells.length < 42) {
      const idx = cells.length - startDow - daysInMonth + 1;
      cells.push({ d: idx, muted: true, date: new Date(y, m + 1, idx) });
    }
    const today = this._startOfDay(new Date());
    this.$('[data-role="grid"]').innerHTML = cells.map(c => {
      const cls = [];
      if (c.muted) cls.push('muted');
      if (this._sameDay(c.date, today)) cls.push('today');
      if (this._val && this._sameDay(c.date, this._val)) cls.push('sel');
      return `<button class="${cls.join(' ')}" data-date="${this._fmtISO(c.date)}">${c.d}</button>`;
    }).join('');
    this.$$('.grid button').forEach(btn => btn.addEventListener('click', () => {
      this._val = this._parse(btn.dataset.date);
      this._sync();
      this._close();
    }));
  }

  _sync() {
    this.setAttribute('value', this._val ? this._fmtISO(this._val) : '');
    this.$('[data-role="text"]').innerHTML = this._fmtDisplay();
    this.emit('change', { value: this._val ? this._fmtISO(this._val) : '' });
    this._renderGrid();
  }

  _fmtDisplay() {
    if (!this._val) return `<span class="placeholder">${attr(this, 'placeholder', 'Select a date')}</span>`;
    return this._val.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  }
  _parse(s) { if (!s) return null; const [y,m,d] = s.split('-').map(Number); return new Date(y, m-1, d); }
  _fmtISO(d) { const p = n => String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`; }
  _sameDay(a, b) { return a && b && a.getFullYear()===b.getFullYear() && a.getMonth()===b.getMonth() && a.getDate()===b.getDate(); }
  _startOfDay(d) { return new Date(d.getFullYear(), d.getMonth(), d.getDate()); }

  get value() { return this._val ? this._fmtISO(this._val) : ''; }
}
customElements.define('ui-datepicker', UIDatepicker);

// task-finder/src/components/UiDatepicker.vue
<template>
  <div class="ui-datepicker">
    <span v-if="label" class="label">{{ label }}</span>

    <div class="trigger-input-group" :data-invalid="isInvalid">
      <input
          class="date-input"
          type="text"
          :value="modelValue"
          :placeholder="placeholder"
          @input="onManualInput"
          @blur="onInputBlur"
      />
      <button class="picker-btn" type="button" title="Open calendar" @click="openPop">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
          <line x1="16" y1="2" x2="16" y2="6"></line>
          <line x1="8" y1="2" x2="8" y2="6"></line>
          <line x1="3" y1="10" x2="21" y2="10"></line>
        </svg>
      </button>
    </div>

    <dialog
        ref="dialogRef"
        class="pop"
        @click="onDialogClick"
        @cancel.prevent="close"
    >
      <div class="drawer-head">
        <span class="title">{{ label || 'Select date' }}</span>
        <button class="drawer-close" title="Close" @click="close">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      </div>

      <div class="drawer-body">
        <div class="head">
          <button
              class="nav-btn"
              :title="mode === 'year' ? 'Previous 12 years' : 'Previous month'"
              @click="onNav(-1)"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="15 18 9 12 15 6"></polyline>
            </svg>
          </button>

          <span v-if="mode === 'year'" class="month" style="cursor: default">
            {{ yearPage }} – {{ yearPage + 11 }}
          </span>
          <button v-else class="month" title="Pick a year" @click="openYearPicker">
            {{ monthName }}
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="6 9 12 15 18 9"></polyline>
            </svg>
          </button>

          <button
              class="nav-btn"
              :title="mode === 'year' ? 'Next 12 years' : 'Next month'"
              @click="onNav(1)"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="9 18 15 12 9 6"></polyline>
            </svg>
          </button>
        </div>

        <!-- Year Grid Mode -->
        <div v-if="mode === 'year'" class="years">
          <button
              v-for="y in yearList"
              :key="y"
              :class="{ sel: y === viewYear }"
              @click="pickYear(y)"
          >
            {{ y }}
          </button>
        </div>

        <!-- Day Grid Mode -->
        <template v-else>
          <div class="dow">
            <div>M</div><div>T</div><div>W</div><div>T</div><div>F</div><div>S</div><div>S</div>
          </div>
          <div class="grid">
            <button
                v-for="(cell, index) in cells"
                :key="index"
                :class="getCellClasses(cell)"
                @click="pick(fmtISO(cell.date))"
            >
              {{ cell.d }}
            </button>
          </div>
        </template>

        <div class="foot">
          <button @click="today">Today</button>
          <button @click="clear">Clear</button>
        </div>
      </div>
    </dialog>
  </div>
</template>

<script>
export default {
  name: 'UiDatepicker',
  props: {
    label: { type: String, default: '' },
    modelValue: { type: String, default: '' },
    placeholder: { type: String, default: 'YYYY-MM-DD' },
    open: { type: Boolean, default: false }
  },
  emits: ['update:modelValue', 'update:open', 'ui-change'],
  data() {
    const now = new Date();
    return {
      isOpen: this.open,
      viewYear: now.getFullYear(),
      viewMonth: now.getMonth(),
      mode: 'day',
      yearPage: now.getFullYear() - (now.getFullYear() % 12),
      isInvalid: false
    };
  },
  computed: {
    parsedValue() {
      return this.parse(this.modelValue);
    },
    monthName() {
      return new Date(this.viewYear, this.viewMonth, 1).toLocaleString(undefined, {
        month: 'long',
        year: 'numeric'
      });
    },
    yearList() {
      return Array.from({ length: 12 }, (_, i) => this.yearPage + i);
    },
    cells() {
      const y = this.viewYear;
      const m = this.viewMonth;
      const first = new Date(y, m, 1);
      const startDow = (first.getDay() + 6) % 7;
      const daysInMonth = new Date(y, m + 1, 0).getDate();
      const prevDays = new Date(y, m, 0).getDate();
      const cells = [];

      for (let i = startDow - 1; i >= 0; i--) {
        cells.push({ d: prevDays - i, muted: true, date: new Date(y, m - 1, prevDays - i) });
      }
      for (let d = 1; d <= daysInMonth; d++) {
        cells.push({ d, muted: false, date: new Date(y, m, d) });
      }
      while (cells.length < 42) {
        const idx = cells.length - startDow - daysInMonth + 1;
        cells.push({ d: idx, muted: true, date: new Date(y, m + 1, idx) });
      }
      return cells;
    }
  },
  watch: {
    open(newVal) {
      this.isOpen = newVal;
    },
    isOpen(newVal) {
      this.$emit('update:open', newVal);
      this.syncDialogState(newVal);
    },
    modelValue: {
      immediate: true,
      handler(newVal) {
        const v = this.parse(newVal);
        if (v) {
          this.viewYear = v.getFullYear();
          this.viewMonth = v.getMonth();
          this.isInvalid = false;
        }
      }
    }
  },
  mounted() {
    if (this.isOpen) {
      this.syncDialogState(true);
    }
  },
  methods: {
    syncDialogState(openState) {
      const dialog = this.$refs.dialogRef;
      if (!dialog) return;

      if (openState) {
        if (!dialog.open) dialog.showModal();
      } else {
        if (dialog.open) dialog.close();
      }
    },
    openPop() {
      this.isOpen = true;
    },
    close() {
      this.isOpen = false;
    },
    onDialogClick(e) {
      const rect = e.currentTarget.getBoundingClientRect();
      const isInDialog =
          rect.top <= e.clientY &&
          e.clientY <= rect.top + rect.height &&
          rect.left <= e.clientX &&
          e.clientX <= rect.left + rect.width;

      if (!isInDialog) {
        this.close();
      }
    },
    onNav(delta) {
      if (this.mode === 'year') {
        this.yearPage += delta * 12;
        return;
      }
      this.viewMonth += delta;
      if (this.viewMonth < 0) {
        this.viewMonth = 11;
        this.viewYear--;
      } else if (this.viewMonth > 11) {
        this.viewMonth = 0;
        this.viewYear++;
      }
    },
    openYearPicker() {
      this.mode = 'year';
      this.yearPage = this.viewYear - (this.viewYear % 12);
    },
    pickYear(y) {
      this.viewYear = y;
      this.mode = 'day';
    },
    emitChange(val) {
      this.$emit('update:modelValue', val);
      this.$emit('ui-change', { value: val });
    },
    pick(iso) {
      this.isInvalid = false;
      this.emitChange(iso);
      this.close();
    },
    today() {
      const val = this.fmtISO(this.startOfDay(new Date()));
      this.isInvalid = false;
      this.emitChange(val);
      this.close();
    },
    clear() {
      this.isInvalid = false;
      this.emitChange('');
      this.close();
    },
    onManualInput(e) {
      const inputVal = e.target.value.trim();
      if (!inputVal) {
        this.isInvalid = false;
        if (this.modelValue !== '') {
          this.emitChange('');
        }
        return;
      }

      const isValidFormat = /^\d{4}-\d{2}-\d{2}$/.test(inputVal);
      const parsed = isValidFormat ? this.parse(inputVal) : null;

      if (parsed) {
        this.isInvalid = false;
        this.viewYear = parsed.getFullYear();
        this.viewMonth = parsed.getMonth();
        this.emitChange(inputVal);
      } else {
        this.isInvalid = true;
      }
    },
    onInputBlur(e) {
      const inputVal = e.target.value.trim();
      if (!inputVal) {
        this.isInvalid = false;
        return;
      }
      this.isInvalid = !this.parse(inputVal);
    },
    getCellClasses(cell) {
      const today = this.startOfDay(new Date());
      return {
        muted: cell.muted,
        today: this.sameDay(cell.date, today),
        sel: this.parsedValue && this.sameDay(cell.date, this.parsedValue)
      };
    },
    parse(s) {
      if (!s) return null;
      const [y, m, d] = s.split('-').map(Number);
      if (!y || !m || !d) return null;
      const dt = new Date(y, m - 1, d);
      return dt.getFullYear() === y && dt.getMonth() === m - 1 && dt.getDate() === d ? dt : null;
    },
    fmtISO(d) {
      const p = n => String(n).padStart(2, '0');
      return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
    },
    sameDay(a, b) {
      return (
          a &&
          b &&
          a.getFullYear() === b.getFullYear() &&
          a.getMonth() === b.getMonth() &&
          a.getDate() === b.getDate()
      );
    },
    startOfDay(d) {
      return new Date(d.getFullYear(), d.getMonth(), d.getDate());
    }
  }
};
</script>

<style scoped>
.ui-datepicker {
  display: inline-block;
  position: relative;
  box-sizing: border-box;
  font-family: system-ui, -apple-system, sans-serif;
}

.label {
  display: block;
  font-size: var(--fs-xs, 12px);
  color: var(--color-text-muted, #666);
  margin-bottom: 6px;
  font-weight: var(--fw-medium, 500);
}

.trigger-input-group {
  display: inline-flex;
  align-items: center;
  background: var(--color-surface, #fff);
  border: 1px solid var(--color-border-strong, #ccc);
  border-radius: var(--radius-md, 6px);
  height: 40px;
  padding: 0 4px 0 12px;
  min-width: 180px;
  box-sizing: border-box;
}

.trigger-input-group[data-invalid="true"] {
  border-color: #dc2626 !important;
}

.trigger-input-group[data-invalid="true"] .date-input {
  color: #dc2626;
}

.date-input {
  flex: 1;
  border: none;
  background: transparent;
  font: inherit;
  font-size: var(--fs-sm, 14px);
  color: var(--color-text, #111);
  outline: none;
  width: 100%;
  min-width: 0;
}

.picker-btn {
  appearance: none;
  border: 0;
  background: transparent;
  cursor: pointer;
  padding: 6px;
  color: var(--color-text-muted, #666);
  border-radius: var(--radius-sm, 4px);
  display: grid;
  place-items: center;
}

/* Dialog Styles */
.pop {
  position: fixed;
  inset: auto 0 0 0;
  width: 100vw;
  max-width: 100vw;
  max-height: 85dvh;
  margin: 0;
  padding: 0;
  border: none;
  border-top-left-radius: 16px;
  border-top-right-radius: 16px;
  box-shadow: 0 -4px 24px rgba(0, 0, 0, 0.15);
  background: var(--color-surface, #fff);
  flex-direction: column;
  overflow: hidden;
}

.pop[open] {
  display: flex;
}

.pop::backdrop {
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: blur(2px);
}

@media (min-width: 640px) {
  .pop {
    inset: 50% auto auto 50%;
    transform: translate(-50%, -50%);
    width: 360px;
    max-width: 90vw;
    border-radius: 12px;
    border: 1px solid var(--color-border, #eee);
    box-shadow: 0 12px 32px rgba(0, 0, 0, 0.2);
  }
}

.drawer-head {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 14px 16px;
  border-bottom: 1px solid var(--color-border, #eee);
}

.drawer-head .title {
  flex: 1;
  font-size: 16px;
  font-weight: 600;
  color: var(--color-text, #111);
}

.drawer-close {
  appearance: none;
  border: 0;
  background: transparent;
  cursor: pointer;
  color: #666;
  width: 28px;
  height: 28px;
  border-radius: 6px;
  display: grid;
  place-items: center;
}

.drawer-body {
  padding: 12px 16px;
  overflow-y: auto;
  flex: 1;
}

.head {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-bottom: 8px;
}

.head .month {
  appearance: none;
  border: 0;
  background: transparent;
  cursor: pointer;
  font: inherit;
  font-weight: 600;
  font-size: 14px;
  color: var(--color-text, #111);
  padding: 4px 8px;
  border-radius: 6px;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  flex: 1;
  justify-content: center;
}

.nav-btn {
  appearance: none;
  border: 0;
  background: transparent;
  cursor: pointer;
  color: #666;
  width: 26px;
  height: 26px;
  border-radius: 6px;
  display: grid;
  place-items: center;
}

.years {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 4px;
  padding: 4px 0;
}

.years button {
  appearance: none;
  border: 0;
  background: transparent;
  font: inherit;
  font-size: 12px;
  color: var(--color-text, #111);
  height: 36px;
  cursor: pointer;
  border-radius: 6px;
}

.years button.sel {
  background: var(--color-primary, #2563eb);
  color: #fff;
  font-weight: 600;
}

.dow,
.grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 2px;
}

.dow div {
  font-size: 10px;
  color: #888;
  text-align: center;
  padding: 4px 0;
  font-weight: 500;
}

.grid button {
  appearance: none;
  border: 0;
  background: transparent;
  font: inherit;
  font-size: 12px;
  color: var(--color-text, #111);
  height: 36px;
  cursor: pointer;
  border-radius: 6px;
  display: grid;
  place-items: center;
}

.grid button.muted {
  color: #aaa;
}

.grid button.today {
  box-shadow: inset 0 0 0 1px var(--color-primary, #2563eb);
  color: var(--color-primary, #2563eb);
  font-weight: 600;
}

.grid button.sel {
  background: var(--color-primary, #2563eb);
  color: #fff;
  font-weight: 600;
}

.foot {
  margin-top: 10px;
  display: flex;
  justify-content: space-between;
  gap: 8px;
}

.foot button {
  appearance: none;
  border: 0;
  background: transparent;
  cursor: pointer;
  color: var(--color-primary, #2563eb);
  font: inherit;
  font-size: 12px;
  font-weight: 500;
}
</style>
