// task-finder-react/src/App.tsx
import { useEffect } from 'react';
import { Routes, Route, Navigate, useNavigate } from 'react-router-dom';
import TabBar from './components/TabBar';
import UpdateOverlay from './components/UpdateOverlay';
import { initNative } from './hooks/useNative';
import { initDeepLinks } from './hooks/useDeepLinks';
import { useAutoUpdater } from './hooks/useOta';

import SandboxPage from './pages/SandboxPage';
import LocationPage from './pages/LocationPage';
import DevicePage from './pages/DevicePage';
import SettingsPage from './pages/SettingsPage';
import TaskDetailPage from './pages/TaskDetailPage';
import RideDetailPage from './pages/RideDetailPage';

export default function App() {
  const navigate = useNavigate();

  // App-wide OTA poller — TanStack Query drives the 15s poll and the
  // auto-apply-on-new-version side effect. Runs regardless of which tab is
  // active so a user stuck on the Sandbox tab still receives hot updates.
  useAutoUpdater(15_000);

  useEffect(() => {
    initNative();
    initDeepLinks(navigate);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="app-shell">
      <main className="app-main">
        <Routes>
          <Route path="/" element={<Navigate to="/sandbox" replace />} />
          <Route path="/sandbox" element={<SandboxPage />} />
          <Route path="/location" element={<LocationPage />} />
          <Route path="/device" element={<DevicePage />} />
          <Route path="/settings" element={<SettingsPage />} />
          <Route path="/task/:id" element={<TaskDetailPage />} />
          <Route path="/ride/:id" element={<RideDetailPage />} />
          <Route path="*" element={<Navigate to="/sandbox" replace />} />
        </Routes>
      </main>
      <TabBar />
      <UpdateOverlay />
    </div>
  );
}

// task-finder/src/App.vue
<template>
  <div class="app-shell">
    <main class="app-main">
      <router-view v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
    </main>
    <TabBar />
    <UpdateOverlay />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import TabBar from './components/TabBar.vue';
import UpdateOverlay from './components/UpdateOverlay.vue';
import { initNative } from './composables/useNative';
import { initDeepLinks } from './composables/useDeepLinks';
import { useOta } from './composables/useOta';

const router = useRouter();
const { startAutoUpdate } = useOta();

onMounted(() => {
  initNative();
  initDeepLinks(router);
  // App-wide OTA poller. Runs regardless of which tab is active so a user
  // stuck on the Sandbox tab still receives hot updates.
  startAutoUpdate(15_000);
});
</script>

<style scoped>
.app-shell {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: var(--bg, #f5f6f8);
}
.app-main {
  flex: 1;
  overflow-y: auto;
  /* Leave room for the fixed bottom tab bar + safe area */
  padding-bottom: calc(72px + env(safe-area-inset-bottom));
}
.fade-enter-active, .fade-leave-active { transition: opacity 0.15s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>
